name: Generate Calendar

on:
  push:
    branches:
      - source
  schedule:
    - cron: '0 8 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
      BUNDLE_WITHOUT: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Mkdir
        run: mkdir public

      - name: Build
        run: bundle exec ruby app.rb

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
